-- SEX_UPON_INTAKE
-- Intact 중성화를 거치지 않은 동물
-- Spayed OR Neutered 중성화를 거친 동물
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM (
    SELECT *
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE 'Intact%'
) AS A
    JOIN ANIMAL_OUTS AS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.SEX_UPON_OUTCOME LIKE 'Spayed%' OR 
    B.SEX_UPON_OUTCOME LIKE 'Neutered%'
ORDER BY ANIMAL_ID ASC;