-- 거래 완료된 물건의 총금액이 70만원 이상인 사람 출력
SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS A
    JOIN USED_GOODS_USER AS B
    ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME
HAVING SUM(A.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;