SELECT SUM(A.SCORE) AS SCORE, A.EMP_NO,
    A.EMP_NAME, A.POSITION, A.EMAIL
FROM (
    SELECT B.SCORE AS SCORE, A.EMP_NO, 
    A.EMP_NAME, A.POSITION, A.EMAIL
    FROM HR_EMPLOYEES AS A
        JOIN HR_GRADE AS B
        ON A.EMP_NO = B.EMP_NO
) A
GROUP BY A.EMP_NAME, A.EMP_NO, A.POSITION, A.EMAIL
ORDER BY SCORE DESC
LIMIT 1;